// Generated by CoffeeScript 1.9.0
(function() {
  var iio, root, _ref,
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  iio = root.iio = (_ref = root.iio) != null ? _ref : {};

  iio.Object = (function() {
    function Object() {
      var others, prop, properties, property, unstructured, value, _i, _j, _len, _len1;
      properties = arguments[0], others = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (!(properties instanceof Object)) {
        unstructured = [properties].concat(unstructured);
        properties = {};
      }
      for (_i = 0, _len = unstructured.length; _i < _len; _i++) {
        property = unstructured[_i];
        if (__indexOf.call(iio.colors, property) >= 0) {
          properties.color = property;
        }
        if (property instanceof Number) {
          if (properties.size == null) {
            properties.size = property;
          } else {

          }
        }
        if (property instanceof Array) {
          if (properties.pos == null) {
            properties.pos = property;
          }
        }
      }
      for (value = _j = 0, _len1 = properties.length; _j < _len1; value = ++_j) {
        prop = properties[value];
        this[prop] = value;
      }
    }

    return Object;

  })();

}).call(this);
