// Generated by CoffeeScript 1.9.1
(function() {
  var iio, ref, root,
    slice = [].slice,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  iio = root.iio = (ref = root.iio) != null ? ref : {};

  iio.Object = (function() {
    function Object() {
      var i, j, len, len1, others, prop, properties, property, unstructured, value;
      properties = arguments[0], others = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (!(properties instanceof Object)) {
        unstructured = [properties].concat(unstructured);
        properties = {};
      }
      for (i = 0, len = unstructured.length; i < len; i++) {
        property = unstructured[i];
        if (indexOf.call(iio.colors, property) >= 0) {
          properties.color = property;
        }
        if (property instanceof Number) {
          if (properties.size == null) {
            properties.size = property;
          } else {

          }
        }
        if (property instanceof Array) {
          if (properties.pos == null) {
            properties.pos = property;
          }
        }
      }
      for (value = j = 0, len1 = properties.length; j < len1; value = ++j) {
        prop = properties[value];
        this[prop] = value;
      }
    }

    return Object;

  })();

}).call(this);
